import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Footer } from "src/components/Footer";
import { Header } from "src/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function About(props) {
  const {
    count,
    isShow,
    handleClick,
    handleDisplay,
    text,
    array,
    handleAdd,
    handleChange,
  } = props;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Header />
          <h1>Index Page</h1>

          {isShow ? <p>{count}</p> : null}
          <button onClick={handleClick}>ボタン</button>
          <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>

          <input type="text" value={text} onChange={handleChange} />
          <button onClick={handleAdd}>追加</button>
          <ul>
            {array.map((item) => {
              return <li key={item}>{item}</li>;
            })}
          </ul>

          <ol>
            <li>
              Get started by editing <code>about.pages</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>
        </main>

        <Footer />
      </div>
    </>
  );
}
